name: Release Workflow
on:
  push:
    paths-ignore:
      - '**.md'
      - '.git**'
    branches-ignore:
      - 'dependabot/**'
  create:
    tags:
      - v*
jobs:
  release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create release
        id: create_release
        if: github.event_name == 'create'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Obscure Slang Translator ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Publish to DockerHub
        if: github.event_name == 'create'
        uses: elgohr/Publish-Docker-Github-Action@3.02
        with:
          name: ijo42/obscureslang
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true

      - name: Publish to DockerHub
        if: github.event_name == 'push'
        uses: elgohr/Publish-Docker-Github-Action@3.02
        with:
          name: ijo42/obscureslang
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          snapshot: true